theme: jekyll-theme-cayman
remote_theme: lewismiddleton/cayman-dark
markdown: GFM

@import "{{ site.theme }}";

  .btn {
    color: #0000ff;
    border-color: #721B67; 
    // background-color: #008CBA;
  } 

  .btn:hover {
    color: #0bb6e1cc;
    text-decoration: none;
    background-color: #7c940ea1;
    border-color: #0000ff;
  }
